---
- name: Deploy HTTPd reverse proxy configuration
  template:
    src: 'httpd/090-filebrowser.conf.j2'
    dest: '/etc/apache2/sites-enabled/090-filebrowser.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
